# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/K4des/OneDrive/Bureau/control_servo/control_servo.srcs/sources_1/import_accelerometre/Square_Root.xci
# IP: The module: 'Square_Root' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/K4des/OneDrive/Bureau/control_servo/control_servo.srcs/sources_1/import_accelerometre/Square_Root_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Square_Root'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/K4des/OneDrive/Bureau/control_servo/control_servo.srcs/sources_1/import_accelerometre/Square_Root.xci
# IP: The module: 'Square_Root' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/K4des/OneDrive/Bureau/control_servo/control_servo.srcs/sources_1/import_accelerometre/Square_Root_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Square_Root'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
